function [EPfieldNames]=ep_fieldNames;
%  [EPfieldNames]=ep_fieldNames;
%       Provides the canonical list of EP file format field names and their order.
%Outputs:
%  EPfieldNames        : Cell array of EP file format field names in the correct order.

%History:
%  by Joseph Dien (2/26/14)
%  jdien07@mac.com
%
%
% modified 3/8/16 JD
% Eliminated support for .power field.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%     Copyright (C) 1999-2018  Joseph Dien
% 
%     This program is free software: you can redistribute it and/or modify
%     it under the terms of the GNU General Public License as published by
%     the Free Software Foundation; either version 3 of the License, or
%     (at your option) any later version.
% 
%     This program is distributed in the hope that it will be useful,
%     but WITHOUT ANY WARRANTY; without even the implied warranty of
%     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%     GNU General Public License for more details.
% 
%     You should have received a copy of the GNU General Public License
%     along with this program.  If not, see <http://www.gnu.org/licenses/>.

EPfieldNames={...
    'data';...
    'noise';...
    'std';...
    'stdCM';...
    'cov';...
    'montage';...
    'fileFormat';...
    'chanNames';...
    'timeNames';...
    'subNames';...
    'cellNames';...
    'trialNames';...
    'facNames';...
    'freqNames';...
    'relNames';...
    'chanTypes';...
    'timeUnits';...
    'subTypes';...
    'cellTypes';...
    'facTypes';...
    'EPver';...
    'ver';...
    'date';...
    'Fs';...
    'baseline';...
    'dataName';...
    'ename';...
    'dataType';...
    'trialSpecs';...
    'trialSpecNames';...
    'subjectSpecs';...
    'subjectSpecNames';...
    'events';...
    'avgNum';...
    'subNum';...
    'covNum';...
    'fileName';...
    'history';...
    'ced';...
    'eloc';...
    'implicit';...
    'facVecT';...
    'facVecS';...
    'facVecF';...
    'facData';...
    'facVar';...
    'facVarQ';...
    'reference';...
    'analysis';...
    'pca';...
    'recTime';...
    'stims';...
    'calibration';...
    'impedances'...
    };
